---
sudo: required

language: python
python: "2.7"

before_install:
 - sudo apt-get update -qq

addons:
  apt:
    packages:
    - python-pip

install:
  # Check ansible version
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

  - ansible-galaxy install grycap.docker

script:
  - ansible-playbook tests/test.yml -i tests/inventory 

  - ansible-playbook tests/test.yml -i tests/inventory -e "swarn_type_of_node=wn"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
