- name: Activate docker port 2375
  lineinfile:
    dest: /etc/default/docker
    regexp: 'DOCKER_OPTS='
    line: 'DOCKER_OPTS="-H unix:///var/run/docker.sock  -H tcp://0.0.0.0:2375"'
  notify: restart docker

- lineinfile:
    dest: /lib/systemd/system/docker.service
    insertbefore: '^ExecStart='
    line: 'EnvironmentFile=/etc/default/docker'
  ignore_errors: yes
  notify:
  - reload docker
  - restart docker

- lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: '^(ExecStart=)(.*)(-H fd://)$'
    line: '\1\2\3 $DOCKER_OPTS'
    backrefs: yes
  ignore_errors: yes
  notify:
  - reload docker
  - restart docker

- name: Init "Swarm Mode" on the first manager.
  shell: docker swarm init
        --listen-addr {{ swarn_manager_address }}:{{ swarn_manager_port }}
        --advertise-addr {{ swarn_manager_address }}
  when: "docker_info.stdout.find('Swarm: active') == -1"

